[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
name = "walrus"
version = "0.1.0"

[dependencies]
failure = "0.1.2"
id-arena = { version = "2.1.0", features = ['rayon'] }
leb128 = "0.2.3"
log = "0.4"
rayon = "1.0.3"
wasmparser = "0.26"

[dependencies.walrus-derive]
path = "./walrus-derive"
version = "=0.1.0"

[dev-dependencies]
env_logger = "0.6"

[workspace]
members = [
    "./walrus-derive",
    "./walrus-tests",
    "./walrus-tests-utils",
]
